#include <exception>

int main(){
    throw std::logic_error("Division by zero");
}
